name: Bandit Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit and reviewdog
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/.local/bin

      - name: Run Bandit
        run: |
          bandit -r . -f json > bandit_report.json || true

      - name: Convert Bandit output to reviewdog format
        run: |
          jq -r '.results[] | "\(.filename):\(.line_number): \(.issue_text) [\(.test_id)]"' bandit_report.json > bandit_reviewdog.txt || true

      - name: Post reviewdog PR comments
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat bandit_reviewdog.txt | $HOME/.local/bin/reviewdog -efm="%f:%l: %m" -name="bandit" -reporter=github-pr-review -filter-mode=file
